---
- name: gathering ax information
  hosts: ax
  gather_facts: no
  
  vars:
  - ansible_connection: network_cli
  - ansible_network_os: ax
  - ansible_become: yes
  - ansible_become_method: enable
  - ansible_become_pass: 'secret2230'

  tasks:
  - name: ax_facts all
    ax_facts:
      gather_subset: all
