---
- name: gathering ax informataion from console using SmartCS
  hosts: smartcs
  gather_facts: no

  vars:
  #ansible_user、ansible_password、ansible_portはユーザごとに異なります。Playbook作成時に変更してください。
  - ansible_connection: network_cli
  - ansible_network_os: ax
  - ansible_become: yes
  - ansible_become_method: enable
  - ansible_become_pass: 'secret2230'
  - ansible_user: "port01"
  - ansible_password: "secret01"
  - ansible_port: 9301

  tasks:
  - name: show commands
    ax_command:
      commands:
        - show version
        - show system
        - show interfaces gigabitethernet 0/1
        - show ip interface
        - show vlan 
        - show access-filter
        - show ntp-client
        - show running-config
    register: result
  
  - name: show command output
    debug:
      msg:
        - '{{ result.stdout_lines[0] }}'
