---
- name: ax show commands
  hosts: ax
  gather_facts: no

  vars:
  - ansible_connection: network_cli
  - ansible_network_os: ax
  - ansible_command_timeout: 60
  - ansible_become: yes
  - ansible_become_method: enable
  - ansible_become_pass: 'secret2230'
  
  tasks:
  - name: gather ax facts all
    ax_facts:
      gather_subset: all
  
  - name: save running-config to localfile
    copy:
      content:  "{{ ansible_net_config }}"
      dest: "./config_{{ ansible_net_hostname }}_{{ now(False, '%Y%m%d_%H%M%S') }}.txt"
