---
- name: ax show commands
  hosts: ax
  gather_facts: no

  vars:
  - ansible_connection: network_cli
  - ansible_network_os: ax
  - ansible_command_timeout: 60
  - ansible_become: yes
  - ansible_become_method: enable
  - ansible_become_pass: 'secret2230'

  tasks:
  - name: execute show commands
    ax_command:
      commands:
        - show version
        - show system
        - show interfaces gigabitethernet 0/1
        - show ip interface
        - show port
        - show vlan 
        - show access-filter
        - show ntp-client
        - show running-config
    register: result
  
  - name: save to localfile
    copy:
      content:  "{{ result.stdout_lines[8] | join('\n') }}"
      dest: ./ax_commands.txt
