---
ntp:
  server:
    - 192.168.127.2
    - 192.168.127.3

snmp:
  community:
    - name: public
      auth: ro
    - name: secret
      auth: rw

syslog:
  server:
    - 192.168.127.2
    - 192.168.127.3