---
- name: add acl configration
  hosts: ax
  
  vars:
  #RHEL_IPはユーザごとに異なります。Playbook作成時に変更してください。
  - ansible_connection: network_cli
  - ansible_network_os: ax
  - ansible_become: yes
  - ansible_become_method: enable
  - ansible_become_pass: 'secret2230'
  - RHEL_IP: '192.168.127.2'

  tasks:
  - name: configure access list
    ax_config:
      lines:
        - 10 permit host {{ RHEL_IP }}
        - 20 deny any
      parents: ip access-list standard "access ansible host only"
      save_when: changed
  
  - name: set access-list to intarface 
    ax_config:
      lines:
        - ip access-group "access ansible host only" in 
      parents: interface vlan 1
      save_when: changed
