---
- name: ax f/w update from console using SmartCS
  hosts: smartcs
  gather_facts: no
  
  vars:
  #ftpserver、ftpuser、ftppass、imgpath、ttynoはユーザごとに異なります。Playbook作成時に変更してください。
  - ansible_connection: network_cli
  - ansible_network_os: smartcs
  - ansible_command_timeout: 300
  - username: 'alaxala'
  - password: 'secret2230'
  - ftpserver: '192.168.127.2'
  - ftpuser: 'rhel01'
  - ftppass: 'secret01'
  - imgpath: '/home/rhel01'
  - verupimg: 'AX2230L20210-01.bin'
  - ttyno: '1'

  tasks:
  - name: ax ppupdate 
    smartcs_tty_command:
      tty: '{{ ttyno }}'
      cmd_timeout: 180
      custom_response: on
      custom_response_delete_nl: on
      recvchar:
      - 'login:'
      - 'Password:'
      - '> '
      - '# '
      - 'Name:'
      - 'ftp> '
      - 'Do you wish to continue? (y/n)'
      sendchar:
      - '{{ username }}'
      - '{{ password }}'
      - 'show version'
      - 'enable'
      - '{{ password }}'
      - 'ftp {{ ftpserver }}'
      - '{{ ftpuser }}'
      - '{{ ftppass }}'
      - 'binary'
      - 'cd {{ imgpath }}'
      - 'get {{ verupimg }} k.img'
      - 'bye'
      - 'ppupdate ramdisk k.img'
      - 'y'
      - '{{ username }}'
      - '{{ password }}'
      - 'show version'
      - 'exit'
    register: result
  
  - name: before/after version and reboot process
    debug:
      msg: 
        - '{{ result.stdout_lines_custom[2].response }}'
        - '{{ result.stdout_lines_custom[12].response }}'
        - '{{ result.stdout_lines_custom[13].response }}'
        - '{{ result.stdout_lines_custom[16].response }}'
