---
- name: login by console
  import_playbook: console_login.yml

- name: gathering config
  import_playbook: console_gathering_config.yml  

- name: logout by console
  import_playbook: console_logout.yml
